#Config for PostgresSql
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cmpg323
    username: docker
    password: postgres
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update