version: "3"
services:
  postgres:
    image: postgres
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
    ports: 
      -  "55002:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      static-network:
        ipv4_address: 172.21.0.1
  account-system:
    image: account-system:latest
    restart: always
    ports: 
      -  "55001:8090"
    networks:
      static-network:
        ipv4_address: 172.21.0.2
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.21.0.0/16
  