server:
  port : 8090
  servlet:
    context-path: "/account-system"
swagger:
  application:
    name: AccountSystem
    description: @project.description@
    version: @project.version@
    contact:
      name: "Petrus AJ Brand - 33219923"
      email: "33219923@student.g.nwu.ac.za"
      url: ""
spring:
  application:
    name: AccountSystem
  mvc:
    servlet:
      path: "/mvc"